In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tqdm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
!gcloud auth login

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&prompt=select_account&response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&access_type=offline


Enter verification code: 4/FgGkGg6r36B78OGSUIt4sqED1y7sEFUwoEDP-PwwrQRormrhH7Y1Iks
If you need to use ADC, see:
  gcloud auth application-default --help

You are now logged in as [wibias9521@gmail.com].
Your current project is [polished-triode-233015].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID


In [0]:
!gsutil -m cp -r gs://swish/dataset/ndsc-advanced/beauty_data_info_train_competition.csv .

Copying gs://swish/dataset/ndsc-advanced/beauty_data_info_train_competition.csv...
- [1/1 files][ 32.2 MiB/ 32.2 MiB] 100% Done                                    
Operation completed over 1 objects/32.2 MiB.                                     


In [0]:
dataset = pd.read_csv('beauty_data_info_train_competition.csv')

In [0]:
dataset.head()

itemid                                              title  \
0   307504               nyx sex bomb pallete natural palette   
1   461203  etude house precious mineral any cushion pearl...   
2  3592295                           milani rose powder blush   
3  4460167                etude house baby sweet sugar powder   
4  5853995       bedak revlon color stay aqua mineral make up   

                                          image_path  Benefits  Brand  \
0  beauty_image/6b2e9cbb279ac95703348368aa65da09.jpg       1.0  157.0   
1  beauty_image/20450222d857c9571ba8fa23bdedc8c9.jpg       NaN   73.0   
2  beauty_image/6a5962bed605a3dd6604ca3a4278a4f9.jpg       NaN  393.0   
3  beauty_image/56987ae186e8a8e71fcc5a261ca485da.jpg       NaN   73.0   
4  beauty_image/9c6968066ebab57588c2f757a240d8b9.jpg       3.0   47.0   

   Colour_group  Product_texture  Skin_type  
0           NaN              NaN        NaN  
1          11.0              7.0        NaN  
2          20.0              6.0        NaN  
3           NaN              6.0        NaN  
4           NaN              6.0        NaN

In [0]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286583 entries, 0 to 286582
Data columns (total 8 columns):
itemid             286583 non-null int64
title              286583 non-null object
image_path         286583 non-null object
Benefits           113556 non-null float64
Brand              238128 non-null float64
Colour_group       121324 non-null float64
Product_texture    244295 non-null float64
Skin_type          58410 non-null float64
dtypes: float64(5), int64(1), object(2)
memory usage: 17.5+ MB


In [0]:
dataset.isnull().sum()

itemid                  0
title                   0
image_path              0
Benefits           173027
Brand               48455
Colour_group       165259
Product_texture     42288
Skin_type          228173
dtype: int64

In [0]:
dataset['Benefits'].value_counts()

1.0    37955
3.0    28419
6.0    26822
4.0    12577
5.0     4930
2.0     2841
0.0       12
Name: Benefits, dtype: int64

In [0]:
#filling nan value in benefits, colour group, and skin_type
dataset['Benefits'].fillna(7, inplace=True)

In [0]:
dataset['Colour_group'].value_counts()

9.0     31457
11.0    15912
22.0    14016
37.0    12991
17.0    11073
20.0     5782
24.0     4943
29.0     4010
32.0     3760
7.0      3181
12.0     2185
27.0     1884
15.0     1833
42.0     1766
25.0     1130
10.0      998
41.0      879
34.0      855
3.0       607
16.0      383
31.0      245
18.0      218
19.0      185
44.0      178
21.0      148
33.0      110
36.0       97
39.0       95
8.0        86
35.0       72
6.0        54
14.0       49
4.0        48
2.0        41
43.0       17
5.0        12
1.0        11
13.0        8
28.0        5
Name: Colour_group, dtype: int64

In [0]:
dataset['Colour_group'].fillna(50, inplace = True)

In [0]:
dataset['Skin_type'].value_counts()

5.0    13061
0.0    12025
6.0     9830
7.0     9077
4.0     5379
1.0     4747
3.0     3187
2.0     1104
Name: Skin_type, dtype: int64

In [0]:
dataset['Skin_type'].fillna(10, inplace = True)

In [0]:
#brand nan nya sedikit, bisa dihilangkan saja
dataset['Brand'].value_counts()
data_brand = dataset.iloc[:,[1,4]]
data_brand = data_brand.dropna()

In [0]:
data_brand.head()

title  Brand
0               nyx sex bomb pallete natural palette  157.0
1  etude house precious mineral any cushion pearl...   73.0
2                           milani rose powder blush  393.0
3                etude house baby sweet sugar powder   73.0
4       bedak revlon color stay aqua mineral make up   47.0

In [0]:
#x variable
title_data = dataset['title']
vectorizer = TfidfVectorizer()
vectorized = vectorizer.fit_transform(title_data)

In [0]:
x_brand = vectorizer.transform(data_brand['title'])

In [0]:
#product_texture nan nya sedikit, bisa dihilangkan saja
data_texture = dataset.iloc[:,[1,6]]
data_texture = data_texture.dropna()

In [0]:
data_texture.head()

title  Product_texture
1  etude house precious mineral any cushion pearl...              7.0
2                           milani rose powder blush              6.0
3                etude house baby sweet sugar powder              6.0
4       bedak revlon color stay aqua mineral make up              6.0
5                            dr pure whitening cream              8.0

In [0]:
x_texture = vectorizer.transform(data_texture['title'])

In [0]:
#Model for Benefit, Colour_Group, Skin_type

attributes = ['Benefits','Colour_group','Skin_type']

#model = naive bayes
from sklearn.naive_bayes import MultinomialNB
naive = MultinomialNB()
for i in attributes:
  x_train,x_test,y_train,y_test = train_test_split(vectorized, dataset[i], train_size = 0.2, random_state = 0)
  naive.fit(x_train,y_train)
  print('Attributes:', i)
  print('Train accuracy score : ', naive.score(x_train, y_train))
  print('Test Accuracy score:', naive.score(x_test, y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


Attributes: Benefits
Train accuracy score :  0.7184555795938307
Test Accuracy score: 0.7100934718036176


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


Attributes: Colour_group
Train accuracy score :  0.6378323679251867
Test Accuracy score: 0.6289566313512194


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


Attributes: Skin_type
Train accuracy score :  0.8195093865587271
Test Accuracy score: 0.8177670576227717


In [0]:
#Model for Benefit, Colour_group, skin_type

attributes = ['Benefits','Colour_group','Skin_type']
list_forest_model = []
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()
for i in attributes:
  forest = RandomForestClassifier()
  x_train,x_test,y_train,y_test = train_test_split(vectorized, dataset[i], train_size = 0.2, random_state = 0)
  forest.fit(x_train,y_train)
  list_forest_model.append(forest)
  print('model : forest_',i)
  print('Attributes:', i)
  print('Train accuracy score : ', forest.score(x_train, y_train))
  print('Test Accuracy score:', forest.score(x_test, y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


model : forest_ Benefits
Attributes: Benefits
Train accuracy score :  0.9477807244050527
Test Accuracy score: 0.8079444490484893


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


model : forest_ Colour_group
Attributes: Colour_group
Train accuracy score :  0.9504675832228348
Test Accuracy score: 0.7949465034217746


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


model : forest_ Skin_type
Attributes: Skin_type
Train accuracy score :  0.9682462139716659
Test Accuracy score: 0.8649216851967357


In [0]:
#iseng nyoba ngetrain pake logistic regression
#Model for Benefit, Colour_group, skin_type

attributes = ['Benefits','Colour_group','Skin_type']
from sklearn.linear_model import LogisticRegression
logs = LogisticRegression()
for i in attributes:
  x_train,x_test,y_train,y_test = train_test_split(vectorized, dataset[i], train_size = 0.2, random_state = 0)
  forest.fit(x_train,y_train)
  print('model : logistic regression_',i)
  print('Attributes:', i)
  print('Train accuracy score : ', forest.score(x_train, y_train))
  print('Test Accuracy score:', forest.score(x_test, y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


model : logistic regression_ Benefits
Attributes: Benefits
Train accuracy score :  0.9475015702421662
Test Accuracy score: 0.8075300850100537


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


model : logistic regression_ Colour_group
Attributes: Colour_group
Train accuracy score :  0.9509212087375253
Test Accuracy score: 0.793738305120231


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


model : logistic regression_ Skin_type
Attributes: Skin_type
Train accuracy score :  0.9681066368902226
Test Accuracy score: 0.8671330806439653


In [0]:
#urutan modelnya 'Benefits','Colour_group','Skin_type', Brand, Product Texture
print(list_forest_model)

[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False), RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False), RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
   

In [0]:
#Separate model for Brand
from sklearn.naive_bayes import MultinomialNB
naive_Brand = MultinomialNB()
from sklearn.ensemble import RandomForestClassifier
forest_Brand = RandomForestClassifier()

model = [naive,forest]
for i in model:
  print(i)
  x_train,x_test,y_train,y_test = train_test_split(x_brand, data_brand['Brand'], train_size = 0.2, random_state = 0)
  i.fit(x_train,y_train)
  print('Attributes: Brand')
  if i == naive:
    print('model : naive_Brand')
    print('Attributes : Naive')
  elif i == forest:
    print('model :forest_Brand')
    print('Attributes : Forest')
    list_forest_model.append(i)
  print('Train accuracy score : ', i.score(x_train, y_train))
  print('Test Accuracy score:', i.score(x_test, y_test))


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


Attributes: Brand
model : naive_Brand
Attributes : Naive
Train accuracy score :  0.757270341207349
Test Accuracy score: 0.7355474716933592
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


Attributes: Brand
model :forest_Brand
Attributes : Forest
Train accuracy score :  0.9996010498687664
Test Accuracy score: 0.9772916961937608


In [0]:
#Separate model for Texture
from sklearn.naive_bayes import MultinomialNB
naive = MultinomialNB()
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()

model = [naive,forest]
for i in model:
  print(i)
  x_train,x_test,y_train,y_test = train_test_split(x_texture, data_texture['Product_texture'], train_size = 0.2, random_state = 0)
  i.fit(x_train,y_train)
  print('Attributes: Brand')
  if i == naive:
    print('Model : Naive')
  elif i == forest:
    print('Model : Forest')
    list_forest_model.append(i)
  print('Train accuracy score : ', i.score(x_train, y_train))
  print('Test Accuracy score:', i.score(x_test, y_test))

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
Attributes: Brand
Model : Naive


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


Train accuracy score :  0.9018195214801776
Test Accuracy score: 0.8914938905831065
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Attributes: Brand
Model : Forest
Train accuracy score :  0.9990994494361325
Test Accuracy score: 0.9806637466996868


In [0]:
#isi list_forest_model_bener benefit, brand, colour_group, product_texture, skin_type
#isi list_forest_model 'Benefits','Colour_group','Skin_type', Brand, Product Texture
list_forest_model_bener = []
list_forest_model_bener.append(list_forest_model[0])
list_forest_model_bener.append(list_forest_model[3])
list_forest_model_bener.append(list_forest_model[1])
list_forest_model_bener.append(list_forest_model[4])
list_forest_model_bener.append(list_forest_model[2])

In [0]:
#start working on val data

In [0]:
!gsutil -m cp -r gs://swish/dataset/ndsc-advanced/beauty_data_info_val_competition.csv .

Copying gs://swish/dataset/ndsc-advanced/beauty_data_info_val_competition.csv...
/ [1/1 files][  7.9 MiB/  7.9 MiB] 100% Done                                    
Operation completed over 1 objects/7.9 MiB.                                      


In [0]:
val_data = pd.read_csv('beauty_data_info_val_competition.csv')

In [0]:
val_data.head()

itemid                                              title  \
0   370855998               flormar 7 white cream bb spf 30 40ml   
1   637234604  maybelline clear smooth all in one bb cream sp...   
2   690282890  murah innisfree eco natural green tea bb cream...   
3   930913462  loreal white perfect day cream spf 17 pa white...   
4  1039280071  hada labo cc cream ultimate anti aging spf 35 ...   

                                          image_path  
0  beauty_image/1588591395c5a254bab84042005f2a9f.jpg  
1  beauty_image/920985ed9587ea20f58686ea74e20f93.jpg  
2  beauty_image/90b40e5710f54352b243fcfb0f5d1d7f.jpg  
3  beauty_image/289c668ef3d70e1d929d602d52d5d78a.jpg  
4  beauty_image/d5b3e652c5822d2306f4560488ec30c6.jpg

In [0]:
x_val = val_data['title']
x_val_vectorized = vectorizer.transform(x_val)

In [0]:
id = []
attrs = ['Benefits','Brand','Colour_group','Product_texture','Skin_type']

for i in range(len(val_data['itemid'])):
  for attr in attrs:
    id.append(str(val_data.iloc[i, 0]) + '_' + attr)

In [0]:
id

['370855998_Benefits',
 '370855998_Brand',
 '370855998_Colour_group',
 '370855998_Product_texture',
 '370855998_Skin_type',
 '637234604_Benefits',
 '637234604_Brand',
 '637234604_Colour_group',
 '637234604_Product_texture',
 '637234604_Skin_type',
 '690282890_Benefits',
 '690282890_Brand',
 '690282890_Colour_group',
 '690282890_Product_texture',
 '690282890_Skin_type',
 '930913462_Benefits',
 '930913462_Brand',
 '930913462_Colour_group',
 '930913462_Product_texture',
 '930913462_Skin_type',
 '1039280071_Benefits',
 '1039280071_Brand',
 '1039280071_Colour_group',
 '1039280071_Product_texture',
 '1039280071_Skin_type',
 '1327710392_Benefits',
 '1327710392_Brand',
 '1327710392_Colour_group',
 '1327710392_Product_texture',
 '1327710392_Skin_type',
 '1328802799_Benefits',
 '1328802799_Brand',
 '1328802799_Colour_group',
 '1328802799_Product_texture',
 '1328802799_Skin_type',
 '1330468145_Benefits',
 '1330468145_Brand',
 '1330468145_Colour_group',
 '1330468145_Product_texture',
 '1330468145_

In [0]:
len(id)

382725

In [0]:
tagging = []

for i in tqdm.tqdm_notebook(range(len(val_data['itemid']))):
  model = list_forest_model_bener[0]
  pred = model.predict(x_val_vectorized[i])
  tagging.append(pred)


Exception ignored in: <bound method tqdm.__del__ of   1%|          | 817/76545 [16:23<11:16, 111.95it/s]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread


In [0]:
import dill

In [0]:
with open('tagging_1.dill', 'wb') as file:
  dill.dump(tagging, file)

In [0]:
with open('tagging_1.dill', 'rb') as file:
    abc = dill.load(file)

In [0]:
abc

[array([6.]),
 array([6.]),
 array([1.]),
 array([6.]),
 array([6.]),
 array([6.]),
 array([1.]),
 array([3.]),
 array([1.]),
 array([6.]),
 array([6.]),
 array([3.]),
 array([3.]),
 array([6.]),
 array([1.]),
 array([6.]),
 array([1.]),
 array([6.]),
 array([6.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([6.]),
 array([6.]),
 array([1.]),
 array([6.]),
 array([3.]),
 array([6.]),
 array([1.]),
 array([6.]),
 array([6.]),
 array([3.]),
 array([6.]),
 array([1.]),
 array([6.]),
 array([7.]),
 array([1.]),
 array([1.]),
 array([1.]),
 array([6.]),
 array([1.]),
 array([3.]),
 array([3.]),
 array([1.]),
 array([7.]),
 array([7.]),
 array([1.]),
 array([1.]),
 array([3.]),
 array([6.]),
 array([1.]),
 array([1.]),
 array([3.]),
 array([7.]),
 array([1.]),
 array([3.]),
 array([7.]),
 array([3.]),
 array([6.]),
 array([1.]),
 array([7.]),
 array([3.]),
 array([6.]),
 array([7.]),
 array([1.]),
 array([3.]),
 array([3.]),
 array([1.]),
 array([3.]),
 array([3.]),
 array([3.]),
 array

In [0]:
model = list_forest_model_bener[1]
for i in tqdm.tqdm_notebook(range(len(val_data['itemid']))):
  pred = model.predict(x_val_vectorized[i])
  tagging.append(pred)

In [0]:
with open('tagging_1.dill', 'wb') as file:
  dill.dump(tagging, file)

In [0]:
model = list_forest_model_bener[2]
for i in tqdm.tqdm_notebook(range(len(val_data['itemid']))):
  pred = model.predict(x_val_vectorized[i])
  tagging.append(pred)

In [0]:
model = list_forest_model_bener[3]
for i in tqdm.tqdm_notebook(range(len(val_data['itemid']))):
  pred = model.predict(x_val_vectorized[i])
  tagging.append(pred)

In [0]:
model = list_forest_model_bener[4]
for i in tqdm.tqdm_notebook(range(len(val_data['itemid']))):
  pred = model.predict(x_val_vectorized[i])
  tagging.append(pred)

In [0]:
len(tagging)

382725

In [0]:
d = {'id':id, 'tagging':tagging}
hasil = pd.DataFrame(d)

In [0]:
hasil.head()

id tagging
0         370855998_Benefits   [6.0]
1            370855998_Brand   [6.0]
2     370855998_Colour_group   [1.0]
3  370855998_Product_texture   [6.0]
4        370855998_Skin_type   [6.0]

In [0]:
def list_to_int(x):
  return int(x[0])

hasil['tagging']=hasil['tagging'].apply(list_to_int)

In [0]:
hasil

id  tagging
0               370855998_Benefits        6
1                  370855998_Brand        6
2           370855998_Colour_group        1
3        370855998_Product_texture        6
4              370855998_Skin_type        6
5               637234604_Benefits        6
6                  637234604_Brand        1
7           637234604_Colour_group        3
8        637234604_Product_texture        1
9              637234604_Skin_type        6
10              690282890_Benefits        6
11                 690282890_Brand        3
12          690282890_Colour_group        3
13       690282890_Product_texture        6
14             690282890_Skin_type        1
15              930913462_Benefits        6
16                 930913462_Brand        1
17          930913462_Colour_group        6
18       930913462_Product_texture        6
19             930913462_Skin_type        1
20             1039280071_Benefits        1
21                1039280071_Brand        1
22         1039280071_Colour_group        6
23      1039280071_Product_texture        6
24            1039280071_Skin_type        1
25             1327710392_Benefits        6
26                1327710392_Brand        3
27         1327710392_Colour_group        6
28      1327710392_Product_texture        1
29            1327710392_Skin_type        6
...                            ...      ...
382695         1824884851_Benefits      307
382696            1824884851_Brand      313
382697     1824884851_Colour_group      243
382698  1824884851_Product_texture      127
382699        1824884851_Skin_type      126
382700         1826670507_Benefits       22
382701            1826670507_Brand      276
382702     1826670507_Colour_group      162
382703  1826670507_Product_texture       71
382704        1826670507_Skin_type       77
382705         1832111687_Benefits      180
382706            1832111687_Brand       47
382707     1832111687_Colour_group      282
382708  1832111687_Product_texture      142
382709        1832111687_Skin_type      237
382710         1832269907_Benefits       62
382711            1832269907_Brand      375
382712     1832269907_Colour_group      266
382713  1832269907_Product_texture      388
382714        1832269907_Skin_type      157
382715         1832929407_Benefits       50
382716            1832929407_Brand       77
382717     1832929407_Colour_group      220
382718  1832929407_Product_texture      379
382719        1832929407_Skin_type      146
382720         1833165562_Benefits       77
382721            1833165562_Brand      349
382722     1833165562_Colour_group       73
382723  1833165562_Product_texture       89
382724        1833165562_Skin_type      379

[382725 rows x 2 columns]

In [0]:
!gsutil -m cp -r gs://swish/predicted/combined_fashion_rfc_dropnull.csv .
!gsutil -m cp -r gs://swish/predicted/mobile_pred_combined_rfc.csv .  

Copying gs://swish/predicted/combined_fashion_rfc_dropnull.csv...
/ [1/1 files][  3.5 MiB/  3.5 MiB] 100% Done                                    
Operation completed over 1 objects/3.5 MiB.                                      
Copying gs://swish/predicted/mobile_pred_combined_rfc.csv...
/ [1/1 files][ 11.4 MiB/ 11.4 MiB] 100% Done                                    
Operation completed over 1 objects/11.4 MiB.                                     


In [0]:
hasil_fashion = pd.read_csv('combined_fashion_rfc_dropnull.csv')
hasil_mobile = pd.read_csv('mobile_pred_combined_rfc.csv')

In [0]:
hasil_fashion

id  tagging
0        381034175_Clothing Material        3
1        721929368_Clothing Material        7
2        800794259_Clothing Material        7
3        962038495_Clothing Material        3
4       1284093055_Clothing Material        4
5       1451569176_Clothing Material        5
6       1639443070_Clothing Material       18
7       1690179744_Clothing Material        7
8       1695487131_Clothing Material       18
9       1703984083_Clothing Material        0
10      1705600680_Clothing Material        7
11      1792870258_Clothing Material       18
12      1862679648_Clothing Material        3
13      1898613826_Clothing Material        5
14      1926409278_Clothing Material        3
15      1049486047_Clothing Material        4
16      1142624296_Clothing Material        7
17      1315482219_Clothing Material        7
18      1569212105_Clothing Material       18
19      1612230932_Clothing Material        5
20      1685961517_Clothing Material        7
21      1726227376_Clothing Material        7
22      1800177596_Clothing Material       18
23      1801394626_Clothing Material        7
24      1807410056_Clothing Material       18
25      1833358668_Clothing Material        5
26      1846770347_Clothing Material        3
27      1499126644_Clothing Material        7
28      1581578582_Clothing Material        3
29      1594382824_Clothing Material        7
...                              ...      ...
238539            1697228611_Sleeves        0
238540            1699547236_Sleeves        3
238541            1708374354_Sleeves        0
238542            1715366921_Sleeves        0
238543            1737603358_Sleeves        0
238544            1758178363_Sleeves        0
238545            1762552713_Sleeves        0
238546            1771172971_Sleeves        1
238547            1774621834_Sleeves        3
238548            1777588088_Sleeves        0
238549            1781710500_Sleeves        0
238550            1792833419_Sleeves        3
238551            1821225505_Sleeves        3
238552            1826937737_Sleeves        0
238553            1832727856_Sleeves        0
238554            1839266150_Sleeves        3
238555            1858129792_Sleeves        0
238556            1867923951_Sleeves        0
238557            1874921602_Sleeves        3
238558            1877942106_Sleeves        0
238559            1880640997_Sleeves        2
238560            1905172674_Sleeves        2
238561            1907377255_Sleeves        2
238562            1912859430_Sleeves        3
238563            1913633531_Sleeves        0
238564            1923580292_Sleeves        3
238565            1931008559_Sleeves        3
238566            1933659164_Sleeves        0
238567            1933723398_Sleeves        3
238568            1937507780_Sleeves        0

[238569 rows x 2 columns]

In [0]:
submission = hasil.append([hasil_mobile,hasil_fashion])

In [0]:
len(hasil_mobile) + len(hasil_fashion)+ len(hasil)

977987

In [0]:
submission.to_csv('Hasil_5.csv',index=False)

In [0]:
def toint(row):
    try:
      n = int(row)
    except:
      n = row
    return n

def dup(row):
  m = '{} {}'.format(row,row)
  return m
submission['tagging'] = submission['tagging'].apply(toint)
submission['tagging'] = submission['tagging'].apply(dup)

In [0]:
submission.tail(10)

id  tagging
150665  1913633531_Sleeves  3.0 3.0
150666  1923580292_Sleeves  3.0 3.0
150667  1926839363_Sleeves  0.0 0.0
150668  1927518121_Sleeves  nan nan
150669  1931008559_Sleeves  3.0 3.0
150670  1933659164_Sleeves  3.0 3.0
150671  1933723398_Sleeves  3.0 3.0
150672  1935512776_Sleeves  3.0 3.0
150673  1937507780_Sleeves  3.0 3.0
150674  1941164568_Sleeves  2.0 2.0

In [0]:
!gsutil -m cp -r Hasil_2.csv gs://swish/predicted/

Copying file://Hasil_2.csv [Content-Type=text/csv]...
-
Operation completed over 1 objects/24.8 MiB.                                     


In [0]:
submission_sample = submission.sample(977987)

In [0]:
submission_sample.to_csv('Hasil_2.csv', index=False)